# Features finales utilisées après preprocessing / encodage
#    → Colonnes réelles présentes dans X_train / X_test

features_processed:
  - Age
  - Weight (kg)
  - Height (m)
  - Gender_Male
  - Workout_Frequency (days/week)
  # - Fat_Percentage

  # One-hot Workout_Type
  - Workout_Type_HIIT
  - Workout_Type_Strength
  - Workout_Type_Yoga

  # # One-hot Body Part
  # - Body Part_Arms
  # - Body Part_Back
  # - Body Part_Chest
  # - Body Part_Forearms
  # - Body Part_Legs
  # - Body Part_Shoulders