# Features utilisées dans le pipeline ML
selected_features:
  # Target
  - Experience_Level

  # Core features
  - Age
  - Gender
  - Weight (kg)
  - Height (m)
  - Workout_Frequency (days/week)
  - Workout_Type
  # - Body Part
  # - Fat_Percentage


# Colonnes optionnelles présentes dans certains datasets
#    Gardées ici pour un usage futur (Transfer Learning / Data Augmentation)
optional_features:
  - BMI
  - sugar_g
  - sodium_mg
  - cholesterol_mg
  - serving_size_g
  - Name of Exercise
  - Sets
  - Reps
  - Target Muscle Group
  - Type of Muscle
  - Benefit
  - rating
  - cooking_method
  - prep_time_min
  - cook_time_min
