# Spécifications "métier" pour l'inférence
# Ces valeurs priment sur l'inférence automatique depuis X_train.

inference_full_columns:

  Age:
    type: integer
    min: 10
    max: 120

  Gender:
    type: string
    enum: ["Male", "Female", "Other", "Prefer not to say"]

  Weight (kg):
    type: number
    min: 30.0
    max: 200.0

  Height (m):
    type: number
    min: 1.50
    max: 2.30

  Fat_Percentage:
    type: number
    min: 11.0
    max: 35.0

  Max_BPM:
    type: number
    min: 159
    max: 200

  Avg_BPM:
    type: number
    min: 119
    max: 170

  Resting_BPM:
    type: number
    min: 49.0
    max: 75.0

  Session_Duration (hours):
    type: number
    min: 0.1
    max: 6

  Workout_Type:
    type: string
    enum: ["Cardio", "Strength", "HIIT", "Yoga", "Pilates", "Other"]

  Experience_Level:
    type: number
    min: 1.0
    max: 3.05

  Workout_Frequency (days/week):
    type: number
    min: 1.94
    max: 5.06

  Difficulty Level:
    type: integer
    enum: [0, 1, 2]
    min: 0
    max: 2

  Body Part:
    type: string
    enum:
      - Abs
      - Arms
      - Back
      - Chest
      - Forearms
      - Legs
      - Shoulders

  Equipment Needed:
    type: string
    enum:
      - Step or Box
      - Parallel Bars or Chair
      - Bench or Sturdy Surface
      - None or Dumbbells
      - Resistance Band
      - Wall
      - None or Dumbbell
      - Dumbbells
      - Dumbbells or Barbell
      - Low Bar or TRX
      - Cable Machine
      - Box or Platform
      - Bench or Chair
      - Resistance Band or Cable Machine
      - Kettlebell
      - Bench or Step
      - Pull-up Bar
      - Barbell
      - Cable Machine or Resistance Band

  diet_type:
    type: string
    enum: ["Paleo", "Low-Carb", "Vegetarian", "Keto", "Vegan", "Balanced"]

  meal_type:
    type: string
    enum: ["Breakfast", "Lunch", "Dinner", "Snack"]


inference_test:

  Age:
    type: integer
    min: 10
    max: 120

  Gender:
    type: string
    enum: ["Male", "Female", "Other", "Prefer not to say"]

  Weight (kg):
    type: number
    min: 30.0
    max: 200.0

  Height (m):
    type: number
    min: 1.50
    max: 2.30

  # Fat_Percentage:
  #   type: number
  #   min: 11.0
  #   max: 35.0

  Max_BPM:
    type: number
    min: 159
    max: 200

  Avg_BPM:
    type: number
    min: 119
    max: 170

  Resting_BPM:
    type: number
    min: 49.0
    max: 75.0

  Session_Duration (hours):
    type: number
    min: 0.1
    max: 6

  Workout_Type:
    type: string
    enum: ["Cardio", "Strength", "HIIT", "Yoga", "Pilates", "Other"]

  Experience_Level:
    type: number
    min: 1.0
    max: 3.05

  Workout_Frequency (days/week):
    type: number
    min: 1.94
    max: 5.06

  # Body Part:
  #   type: string
  #   enum:
  #     - Abs
  #     - Arms
  #     - Back
  #     - Chest
  #     - Forearms
  #     - Legs
  #     - Shoulders