# Spécifications "métier" pour l'inférence
# Ces valeurs priment sur l'inférence automatique depuis X_train.
inference:

  Age:
    type: integer
    min: 18
    max: 60

  Gender:
    type: string
    enum: ["Male", "Female", "Other", "Prefer not to say"]

  Weight (kg):
    type: number
    min: 30.0
    max: 200.0

  Height (m):
    type: number
    min: 1.50
    max: 2.30

  # Fat_Percentage:
  #   type: number
  #   min: 11.0
  #   max: 35.0

  Workout_Frequency (days/week):
    type: number
    min: 0
    max: 7

  Workout_Type:
    type: string
    enum: ["Cardio", "Strength", "HIIT", "Yoga", "None"]



  # Body Part:
  #   type: string
  #   enum:
  #     - Abs
  #     - Arms
  #     - Back
  #     - Chest
  #     - Forearms
  #     - Legs
  #     - Shoulders