# Valeurs par défaut pour l'UI (Gradio)
# Ces valeurs sont utilisées pour pré-remplir les champs de l'interface.

UI_DEFAULTS:
  Age: 55.92
  Gender: "Female"
  Weight (kg): 84.07
  Height (m): 1.63
  Workout_Type: "Yoga"
  # Body Part: "Back"
  Workout_Frequency (days/week): 3.97
  # Fat_Percentage: 32.08817620708069
