# Exemples UI affichés sous les sliders / inputs
# Chaque entrée représente un exemple complet d'utilisateur typique.
UI_EXAMPLES:

  - Experience_Level: 2.01
    Age: 34.91
    Gender: "Male"
    Weight (kg): 65.27
    Height (m): 1.62
    Workout_Type: "Strength"
    Workout_Frequency (days/week): 3.99

  - Experience_Level: 2.01
    Age: 23.37
    Gender: "Female"
    Weight (kg): 56.41
    Height (m): 1.55
    Workout_Type: "HIIT"
    Workout_Frequency (days/week): 4.0

  - Experience_Level: 1.02
    Age: 33.2
    Gender: "Female"
    Weight (kg): 58.98
    Height (m): 1.67
    Workout_Type: "Cardio"
    Workout_Frequency (days/week): 2.99

  - Experience_Level: 1.99
    Age: 38.69
    Gender: "Female"
    Weight (kg): 93.78
    Height (m): 1.7
    Workout_Type: "HIIT"
    Workout_Frequency (days/week): 3.99

  - Experience_Level: 2.0
    Age: 45.09
    Gender: "Male"
    Weight (kg): 52.42
    Height (m): 1.88
    Workout_Type: "Strength"
    Workout_Frequency (days/week): 4.0

  - Experience_Level: 1.0
    Age: 53.19
    Gender: "Female"
    Weight (kg): 105.05
    Height (m): 1.84
    Workout_Type: "Yoga"
    Workout_Frequency (days/week): 3.02

  - Experience_Level: 3.0
    Age: 23.17
    Gender: "Male"
    Weight (kg): 58.41
    Height (m): 1.78
    Workout_Type: "Strength"
    Workout_Frequency (days/week): 4.96

  - Experience_Level: 2.01
    Age: 55.92
    Gender: "Female"
    Weight (kg): 84.07
    Height (m): 1.63
    Workout_Type: "Yoga"
    Workout_Frequency (days/week): 3.97
